server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://discoveryUser:discoveryPassword@localhost:8761/eureka/

spring:
    application:
        name: discovery-service
    security:
        user:
            name: discoveryUser
            password: discoveryPassword
            roles: SYSTEM
