server:
    port: 8082

spring:
    application:
        name: shop-service
    redis:
        host: localhost
        port: 6379
    jpa:
        hibernate:
            ddl-auto: none

management:
    security:
        sessions: never
