server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tupchiienko/online-shop-config.git
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_shop_db
    username: postgres
    password: postgres
    name: online_shop_db

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    service-url:
      defaultZone: http://discoveryUser:discoveryPassword@localhost:8761/eureka/
